apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-db-persistent
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
    - ReadOnlyMany
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /tmp/db