spring:
  datasource:
    # connect to mysql service deployed in k8s
#    url: jdbc:mysql://mysql/test?useUnicode=true&characterEncoding=utf-8&userSSL=false&serverTimezone=GMT%2B8
    # connect to wsl's mysql server
    url: jdbc:mysql://localhost:13306/test?useUnicode=true&characterEncoding=utf-8&userSSL=false&serverTimezone=GMT%2B8
    username: root
#    password: dGVzdA==
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      filters: stat
      web-stat-filter:
        enabled: true
        url-pattern: /*
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
#  redis:
#    database: 0
#    host: localhost
#    port: 6379
mybatis:
  type-aliases-package: cn.edu.djtu.db.entity
  mapper-locations: classpath:mapper/*.xml
  type-handlers-package: cn.edu.djtu.db.entity.handler
  configuration:
    map-underscore-to-camel-case: true
server:
  port: 8302
